name: UI React deploy
on:
  push:
    paths:
      - 'services/react_ui/**'
      - '.github/workflows/ui_react.yml'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-west-1
  APP_ENVIRONMENT: development
  VITE_VUE_APP_API_URL: https://e3gq72bill.execute-api.eu-west-1.amazonaws.com/development/api  # new

jobs:
  deploy-development:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16]
    defaults:
      run:
        working-directory: services/react_ui
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install serverless
        run: npm install -g serverless@3.0.0
      - name: Install NPM dependencies
        run: npm install
